# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acfaf224caa113532ad74c761f70b92be78923b8c7202cc4ae4dd70d393ad7e6a63343ae6b72dc62ec4ecd2f27b2930eddfdacdf1ac23c530ef033bcf25c7483

test:
  secret_key_base: 95c4d3d552dc4f8164cd88fe2acfdc3a1745598e88db0c4b82e6e0e011ea479a2e8fcce0b5d575cf52b157c4df70bf70da3c3b4158b28447bb27ce09c89282b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
